【网站信息】:
  程序名称: 'web1 - Mirror V3.0 by TG@seo898'
  识别代码: 'web1' # 响应标头识别码 禁止填写中文
  TGBot-Token: 'admin.domain.com'
  TG用户名: 'admin'
  api-token: 'seo898'
  激活码: 'yHZc0hhjttAncrwpw4iHog==|oo4KHfAy4YWMvdL+CqmXW7SOedyoi1dNVRDa3r4b5iM='

【镜像设置】:
  硬盘阈值: # 达到阈值后，会关闭 “自动建站” 和 “生成内页配置” 功能，此时程序不再新增任何数据（除日志外）
    硬盘可用空间小于: 15 # G  单位：GB
    硬盘已用空间百分比超过: 95 # %  百分比
    自动删除: true # 删除开关 打开后：达到阈值后开始以“【数据删除策略】”删除数据
  本站:
    自动建站: true # 关闭时: 不自动生成首页网站配置 www.domain.com_zh_www.target.com_zh.yml
    生成内页配置: true # 关闭时: 不自动生成内页配置 domain.com\about.html_zh.yml （此功能一般在磁盘爆满后使用）
    自动建站功能自动恢复: true # 开启时: 在未达到硬盘阈值时会自动打开“自动建站”
    生成内页配置自动恢复: true # 开启时: 在未达到硬盘阈值时会自动打开“生成内页配置”
    语言: 'zh' # zh:中文 | zh-Hant:繁体中文 | en:英文 | pt:葡萄牙文
    首页定时更新: 1 # 单位：天 填写0 表示永不更新
    内页自定义TDK: false # 开启后，内页会引用配置文件中的TDK
    标题转码: true
    关键词转码: true
    描述转码: true
    目录功能: # 默认目录模板路径为：site/template
      模板模式: '404' # 关闭:不调用模板 | 404:目标站404时返回模板 | 泛目录:所有内页调用模板，缓存页面| 蜘蛛池:所有内页调用模板，不缓存页面
      动态标签: ['{外链}','{轮链}'] # 动态标签不会缓存，每次刷新变动
      目录内页自定义TDK: true # 开启后，目录内页会引用配置文件中的TDK
      网站地图链接数量: 500 # 指定sitemap1.txt  sitemap123.xml 中随机生成的链接数量
      网站地图链接格式: '{当前base_url}{网站地图专用随机内链}' # 此处引用标签 详情至 config/标签.yml
  目标站:
    文档路径: 'doc/中文目标站.txt'
    缓存页面上限: 500 # 0:表示无限页面 | 100:表示最多100个html页面   # 设置html页面缓存数量，超过则删除一个最旧页面
    缓存文件名: ['.css', '.js'] # 静态文件保存到本地 '.css', '.js', '.png', '.jpg', '.ico','.svg', '.gif', '.jpeg'
    静态文件远程调用: false # 开启后所有静态文件都走远程调用，网络压力加大，硬盘压力减小
    仅缓存翻译数据: true # 开启后只会保存翻译后的网页，不会再同时保存源网页和翻译后的网页
    SEO功能: # 注意！seo功能是在下载源码时进行处理后直接保存，请务必在开站前设置好所有seo功能，后期不要再更改。如更改，需要将已经下载的目标站源码删除，才能生效。
      开启缓存图片翻转: true # ‘静态文件远程调用’需关闭，且‘缓存文件名’中需加入'.png', '.jpg', '.ico','.svg', '.gif', '.jpeg' 图片翻转方可生效
      删除alt&title属性: true
      随机插入meta标签: true
      随机插入link标签: true
      随机插入class属性: true
      随机插入内联style属性: true
      html代码压缩: false
      js加密混淆: true # “静态文件远程调用”需关闭，缓存js文件时生效
      css加密混淆: true # “静态文件远程调用”需关闭，缓存css文件时生效
      首页链接映射: true # 开启后，首页所有内链包括文件链接，将映射为全新的链接，与原目标站的链接进行差异化

【数据删除策略】:
  web:
    删除无主配置内页: true # 删除不存在“网站配置”的“网站内页配置”文件
    删除非主配置语言内页: true # 删除所有非“网站配置”lang的“网站内页配置”文件
    页面删除策略: # 注意！！！此功能在不清楚使用方法时，请勿随意设置和开启！错误的设置会导致页面数据永久丢失！
      删除开关: true # 开启后，删除脚本运行时会根据“页面删除策略”来自动删除正常页面
      删除主站配置: false # 开启后，允许删除主站www和根域名的配置文件
      删除泛站配置: true # 开启后，允许删除泛站的配置文件
      页面删除数量: 100 # 每次删除脚本运行时删除正常页面的总数
      页面生成时间大等于: 30 # 单位：天 30 表示页面配置创建达到30天，开始判断删除页面 填写0 表示不判断页面生成时间，直接开始判断删除页面
      判断页面蜘蛛数据: # 根据页面蜘蛛访问数量来删除 判断任意一个符合则删除
        百度蜘蛛: "0" # "0" 表示跳过判断
        搜狗蜘蛛: "0" # "<1" 表示页面蜘蛛数量小于1则删除，判断任意一个符合条件则删除
        神马蜘蛛: "0" # ">10" 表示页面蜘蛛数量大于10则删除，判断任意一个符条件合则删除
        头条蜘蛛: "0"
        必应蜘蛛: "0"
        360蜘蛛": "0"
        谷歌图片蜘蛛": "0"
        谷歌蜘蛛: "<1"
        雅虎蜘蛛: "0"
        其它蜘蛛: "0"
        普通用户: "0"
  target:
    删除未使用目标站: true # 删除所有未被“网站配置”引用的“目标站”文件夹
    删除目标站未使用语言: true # 删除所有未被“网站配置”引用的“目标站lang”文件夹
    删除非200页面: true
    删除非200页面type: false

【访问策略】:
  非绑定域名访问: true
  IP与非域名访问: false
  搜索来路直跳广告: false
  普通用户直跳广告: false
  根域名跳WWW: false
  UA黑名单: 'Scrapy|Curl|HttpClient|UniversalFeedParser|lightDeckReports Bot|heritrix|Java|Bytespider|YandexBot|FlightDeckReports|Indy Library|BOT/0.1|DigExt|Feedly|Swiftbot|oBot|Python-urllib|CrawlDaddy|YYSpider|JikeSpider|ZmEu|MJ12bot|WebZIP|Apache-HttpAsyncClient|HttpClient|WinHttp|jaunty|Alexa Toolbar|LinkpadBot|Microsoft URL Control|node-superagent|Ezooms|Jullo|SemrushBot|FetchURL|AhrefsBot|EasouSpider|java/|CoolpadWebkit|Linguee Bot|ApacheBench|AskTbFXTV|FeedDemon'
  IP黑名单: '888.888.888.888|88.88.88.88'

【全站代码插入】: # 一般用于插入网站统计和JS广告 过滤IP填写本地IP可过滤掉插入的广告
  过滤IP: ['8.8.8.8']
  <head>后: ''
  </head>前: '<script language="javascript" src="/_/static/js/ad.js" type="text/javascript"></script>'
  <body>后: ''
  </body>前: '<script language="javascript" src="/_/static/js/tongji.js" type="text/javascript"></script>'

【蜘蛛设置】:
  记录蜘蛛日志: true # 开启则记录蜘蛛访问数据
  蜘蛛日志保留天数: 30 # 注意：超过天数会自动删除过期文件夹
  蜘蛛访问开关:
    百度蜘蛛: true
    搜狗蜘蛛: true
    神马蜘蛛: true
    头条蜘蛛: true
    必应蜘蛛: true
    360蜘蛛: true
    谷歌图片蜘蛛: false
    谷歌蜘蛛: true
    雅虎蜘蛛: false
    其它蜘蛛: false
    其他蜘蛛: false
    普通用户: true
  蜘蛛静态文件访问开关: true
