title:
    - '{关键词1}-{关键词1}{随机后缀}-{关键词1}{随机后缀}'
    - '{关键词1}-{关键词1}{随机后缀}'
    - '{关键词1}-{关键词2}{随机后缀}-{关键词3}{随机后缀}'
    - '{关键词1}-{关键词1}{随机后缀}'
    - '{关键词1}-{关键词2}-{关键词3}'
    - '{关键词1}-{关键词2}'
    - '{关键词1}'
keywords: 
    - '{关键词1},{关键词2},{关键词3}'
    - '{关键词1},{关键词2}'
des:
    - '{描述BC({关键词1})}'