【自定义】:
  标题: 
    - '{关键词1}（{中国省名}）{公司行业}有限责任公司' # 搜狗 360 目录
    - '{关键词1}（{中国省名}）{公司行业}股份有限公司' # 搜狗 360 目录
  内链: 
    - '//{随机4-8数字字符}.{随机域名}'
    - '/{随机4-8字符}.html'
    - '{随机外推网址}{关键词}-【{随机落地域名}】-{关键词}-【{随机落地域名}】-{随机3字符}'
  泛站内链: //{随机4-8数字字符}.{当前根域名}/{随机4-8字符}.html
  泛站: //{随机4-8数字字符}.{当前根域名}
  外链: 
    - //{随机4-8数字字符}.{随机域名}
    - '{随机外推网址}{关键词}-【{随机落地域名}】-{关键词}-【{随机落地域名}】-{随机3字符}'
  随机版本: V{随机1数字}.{随机2数字}.{随机2数字}
  新闻网内容: 
    - <p>{随机句子({关键词},1)}</p><p>{随机句子({关键词},1)}</p><p>{随机句子({关键词},1)}</p>
    - <p>{随机句子({关键词},0-1)}</p><p>{随机句子({关键词},0-1)}{随机句子({关键词},0-1)}</p><p>{随机句子({关键词},0-1)}{随机句子({关键词},0-1)}</p><p>{随机句子({关键词},0-1)}</p>
    - <p>{随机句子({关键词},1)}</p><p>{随机句子({关键词},0-1)}</p><p>{随机句子({关键词},0-1)}{随机句子({关键词},0-1)}</p><p>{随机句子({关键词},0-1)}</p>
    - <p>{随机句子({关键词},0-1)}{随机句子({关键词},0-1)}</p><p>{随机句子({关键词},0-1)}{随机句子({关键词},0-1)}</p><p>{随机句子({关键词},0-1)}</p><p>{随机句子({关键词},0-1)}</p>
    - <p>{随机句子({关键词},0-1)}{随机句子({关键词},0-1)}</p><p>{随机句子({关键词},0-1)}{随机句子({关键词},0-1)}{随机句子({关键词},0-1)}</p><p>{随机句子({关键词},0-1)}</p>
  网站地图:
    - http://{当前域名}/sitemap.xml
    - http://{当前域名}/sitemap.txt
  网站地图专用随机内链:
    - /{随机4-10字符}/
    - /{随机4-10字符}.html
    - /{随机4-8字符}/{随机4-8字符}/
    - /{随机4-8字符}/{随机4-8数字}.html
    - /{随机3-6字符}/{英文单词}.html
    - /{随机3-6字符}/{英文单词}/
    - /{英文单词}-{英文单词}-{英文单词}
    - /{英文单词}-{英文单词}
  随机内链:
    - /{随机4-10字符}/
    - /{随机4-10字符}.html
    - /{随机4-8字符}/{随机4-8字符}/
    - /{随机3-6字符}/{英文单词}.html
    - /{随机3-6字符}/{英文单词}/
  轮链: 
    - http://{随机4-8数字字符}.{随机域名}
    - '{随机外推网址}{关键词}-【{随机落地域名}】-{关键词}-【{随机落地域名}】-{随机3字符}'

【文本抽取】: # 随机抽取文档中的一条
  随机目标站: doc/目标站.txt
  英文目标站: doc/英文目标站.txt
  随机关键词: doc/关键词
  关键词: doc/关键词.txt
  辅助描述: doc/辅助描述.txt
  随机后缀: doc/后缀.txt
  描述: doc/描述.txt
  描述BC: doc/描述库BC.txt
  标题: doc/新闻标题.txt
  人物名称: doc/人名.txt
  公司行业: doc/公司行业.txt
  中国省名: doc/中国各省简称.txt
  新闻网标题: doc/新闻标题
  随机域名: config/域名.txt
  随机图片外链: doc/图片外链.txt
  标题名称: doc/网站名.txt
  网站名称: doc/网站名.txt
  英文单词: doc/新英文单词.txt
  随机句子: doc/新闻文章
  句子: doc/新闻文章
  随机外推网址: doc/外推网址.txt
  随机落地域名: doc/落地域名.txt

【文件抽取】:  # 随机抽取文件中的一个 返回“文件路径”
  随机图片: _/static/image/img
  随机头像: _/static/image/profile_photo
  新闻图片: _/static/image/news_pic
  # 随机模板: site/template

【字符生成】:
  随机数字: '0123456789'
  随机字符: abcdefghijklmnopqrstuvwxyz
  随机数字字符: 0123456789abcdefghijklmnopqrstuvwxyz
  随机大小字符: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  随机大小数字字符: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  随机短字符: abcdefghijklmnopqrstuvwxyz

【信息获取】:
  - 年 # 2023
  - 年2 # 2023年
  - 年月 # 2023-12
  - 年月2 # 2023年12月
  - 年月日 # 2023-12-12
  - 年月日2 # 2023年12月12日
  - 今日时间 # 2023-12-12 22:17:41
  - 今日时间2 # 2023年12月12日 22:17:41
  - 当前时间 # 22:17:41
  - 当前根域名 # seo898.com
  - 当前域名 # www.seo898.com
  - 当前url # http://www.seo898.com/abc/cbd.html
  - 当前base_url # http://www.seo898.com
  - title # 标签处理后的 <title>内容
  - keywords # 标签处理后的 <meta keywords>关键词内容
  - keyword # 标签处理后的 <meta keywords>内容中的第一个关键词
  - keywords[0] # 标签处理后的 <meta keywords>内容中的第一个关键词
  - keywords[1] # 标签处理后的 <meta keywords>内容中的第二个关键词 没有则返回第一个
  - keywords[2] # 标签处理后的 <meta keywords>内容中的第三个关键词 没有则返回第一个
  - description # 标签处理后的 <meta description>描述内容
  - des # 标签处理后的 <meta description>描述内容

【功能函数】: # 所有函数都是以下划线开头结尾
  - _核心词替换_ # {_核心词替换_({随机句子},{关键词1},0-1)}  一般用于替换文章核心词
  - _生成相关词_ # {_相关词_({关键词1})}  一般用于生成标题
  - _GPT获取标题_ # GPT获取标题({关键词}) 调用GPT以关键词生成一个标题
